set_attribute -type boolean [get_pins instBuf/instBuffer/clk] is_pad true
set_attribute -type boolean [get_pins activeList/activeList/clk] is_pad true
set_attribute -type boolean [get_pins activeList/ldViolateVector/clk] is_pad true
set_attribute -type boolean [get_pins amt/AMT/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbTag0/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbTag1/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbTag2/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbTag3/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbData0/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbData1/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbData2/clk] is_pad true
set_attribute -type boolean [get_pins fs1/btb/btbData3/clk] is_pad true
set_attribute -type boolean [get_pins fs1/bp/CounterTable_even/clk] is_pad true
set_attribute -type boolean [get_pins fs1/bp/CounterTable_odd/clk] is_pad true
set_attribute -type boolean [get_pins rename/specfreelist/FREE_LIST/clk] is_pad true
set_attribute -type boolean [get_pins rename/RMT/RenameMap/clk] is_pad true
