# Dump of design planning placement blockages as soft blockages
create_placement_blockage -type soft -bbox {1640.315000 177.505000 1751.120000 228.782000} -name blockage1_over_rename/RMT/RenameMap
create_placement_blockage -type soft -bbox {95.270000 7.760000 165.795000 57.079000} -name blockage2_over_rename/specfreelist/FREE_LIST
create_placement_blockage -type soft -bbox {578.520000 30.435000 638.480000 56.150000} -name blockage3_over_fs1/bp/CounterTable_even
create_placement_blockage -type soft -bbox {578.520000 9.200000 638.480000 34.915000} -name blockage4_over_fs1/bp/CounterTable_odd
create_placement_blockage -type soft -bbox {794.775000 100.105000 949.520000 194.212000} -name blockage5_over_fs1/btb/btbTag0
create_placement_blockage -type soft -bbox {794.775000 9.200000 949.520000 103.307000} -name blockage6_over_fs1/btb/btbTag1
create_placement_blockage -type soft -bbox {639.255000 100.105000 794.000000 194.212000} -name blockage7_over_fs1/btb/btbTag2
create_placement_blockage -type soft -bbox {639.255000 9.200000 794.000000 103.307000} -name blockage8_over_fs1/btb/btbTag3
create_placement_blockage -type soft -bbox {1105.815000 100.105000 1260.560000 194.212000} -name blockage9_over_fs1/btb/btbData0
create_placement_blockage -type soft -bbox {1105.815000 9.200000 1260.560000 103.307000} -name blockage10_over_fs1/btb/btbData1
create_placement_blockage -type soft -bbox {950.295000 100.105000 1105.040000 194.212000} -name blockage11_over_fs1/btb/btbData2
create_placement_blockage -type soft -bbox {950.295000 9.200000 1105.040000 103.307000} -name blockage12_over_fs1/btb/btbData3
create_placement_blockage -type soft -bbox {19.755000 8.550000 90.280000 57.869000} -name blockage13_over_amt/AMT
create_placement_blockage -type soft -bbox {1677.215000 52.285000 1747.740000 101.604000} -name blockage14_over_activeList/activeList
create_placement_blockage -type soft -bbox {1606.690000 52.285000 1677.215000 101.604000} -name blockage15_over_activeList/ctrlActiveList
create_placement_blockage -type soft -bbox {1606.690000 7.765000 1677.215000 57.084000} -name blockage16_over_activeList/targetAddrActiveList
create_placement_blockage -type soft -bbox {1677.215000 7.765000 1747.740000 57.084000} -name blockage17_over_activeList/ldViolateVector
create_placement_blockage -type soft -bbox {1521.635000 177.505000 1630.800000 238.194000} -name blockage18_over_instBuf/instBuffer


# ======== The following blockages are generated by congestion driven channel resizing ========

create_placement_blockage -type soft -bbox {1624.085000 180.390000 1647.030000 220.135000} -name blockage0_over_refined_channel
